import { Router } from "express";
import { authCheck } from "../../middleware/jwt.middleware";
import { BillingController } from "./billing.controller";

const router = Router();
const authenticated = authCheck(["superAdmin", "admin", "tenant", "user", "superAnalyst", "compliance"]);
router.get("/summary", authenticated, BillingController.summary);
router.get("/usage", authenticated, BillingController.usage);
router.get("/plans", authenticated, BillingController.plans);
router.post("/checkout", authenticated, BillingController.checkout);
router.post("/wallet-topup/checkout", authenticated, BillingController.walletTopupCheckout);
router.get("/checkout/:session_id/confirm", authenticated, BillingController.confirmCheckout);
router.get("/subscriptions", authenticated, BillingController.subscriptions);
router.get("/transactions", authenticated, BillingController.transactions);
router.get("/transactions/:transaction_uuid", authenticated, BillingController.transaction);
router.post("/subscriptions/:subscription_uuid/cancel", authenticated, BillingController.cancelSubscription);
router.get("/capabilities", authenticated, BillingController.capabilities);
const superAdmin = authCheck(["superAdmin"]);
router.get("/admin/plans", superAdmin, BillingController.adminPlans);
router.post("/admin/plans", superAdmin, BillingController.adminPlans);
router.patch("/admin/plans/:plan_uuid", superAdmin, BillingController.adminPlanUpdate);
router.delete("/admin/plans/:plan_uuid", superAdmin, BillingController.adminPlanDelete);
router.get("/admin/rates", superAdmin, BillingController.adminRates);
router.put("/admin/rates", superAdmin, BillingController.adminRates);
router.get("/admin/subscriptions", superAdmin, BillingController.adminSubscriptions);
router.get("/admin/transactions", superAdmin, BillingController.adminTransactions);
router.get("/admin/users/:user_uuid/wallet", superAdmin, BillingController.adminUserWallet);
router.post("/admin/users/:user_uuid/credits", superAdmin, BillingController.adminGrantCredits);
export default router;
